version: '3.9'

services:
  activemq:
    image: apache/activemq-classic
    ports:
      - "61616:61616"
      - "8161:8161"
    networks:
      - red-consumidor

  jmssensordata:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - activemq
    networks:
      - red-consumidor

networks:
  red-consumidor: