version: '3.9'

services:
  mockupapi:
    container_name: mockAPI
    image: mockupapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PUERTO_APP:-8080}:8080
    env_file:
      - .env
    depends_on:
      - db
    restart: always
    networks:
      - mockapi-red
    volumes:
      - mockapi-volumen:/var/lib/web

  db:
    image: mysql:8.0.23
    ports:
      - ${PUERTO_DB:-3306}:3306
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - mockapi-red

  phpmyadmin:
    image: phpmyadmin:5.1.1
    env_file:
      - .env
    ports:
      - ${PUERTO_PHPMYADMIN}:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - mockapi-red
    depends_on:
      - db

networks:
  mockapi-red:

volumes:
  mockapi-volumen:
  db-data: